using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Chatter.SourceGenerators.Discovery;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Chatter.SourceGenerators
{
    [Generator(LanguageNames.CSharp)]
    public sealed class AllCommandsBehaviorRegistrationGenerator : IIncrementalGenerator
    {
        private const string RegisterForAllCommandsAttributeMetadataName = "Chatter.CQRS.Pipeline.RegisterForAllCommandsAttribute";
        private const string CommandBehaviorOpenMetadataName = "Chatter.CQRS.Pipeline.ICommandBehavior`1";
        private const string CommandMetadataName = "Chatter.CQRS.Commands.ICommand";
        private const string ChatterCqrsAssemblySimpleName = "Chatter.CQRS";

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var behaviorTypes = context.SyntaxProvider.ForAttributeWithMetadataName(
                    RegisterForAllCommandsAttributeMetadataName,
                    predicate: static (node, _) => node is ClassDeclarationSyntax,
                    transform: static (ctx, _) => (INamedTypeSymbol)ctx.TargetSymbol)
                .Collect();

            context.RegisterSourceOutput(
                behaviorTypes.Combine(context.CompilationProvider),
                static (spc, pair) => Execute(pair.Right, pair.Left, spc));
        }

        private static void Execute(Compilation compilation, ImmutableArray<INamedTypeSymbol> behaviorTypes, SourceProductionContext context)
        {
            if (behaviorTypes.IsDefaultOrEmpty)
            {
                return;
            }

            var commandBehaviorOpen = compilation.GetTypeByMetadataName(CommandBehaviorOpenMetadataName);
            var commandInterface = compilation.GetTypeByMetadataName(CommandMetadataName);

            if (commandBehaviorOpen is null || commandInterface is null)
            {
                return;
            }

            var commandTypes = CompilationTypeWalker
                .FindAccessibleCandidateTypes(compilation, ChatterCqrsAssemblySimpleName)
                .Where(t => CompilationTypeWalker.Implements(t, commandInterface))
                .Distinct(SymbolEqualityComparer.Default)
                .OfType<INamedTypeSymbol>()
                .ToList();

            if (commandTypes.Count == 0)
            {
                return;
            }

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
            sb.AppendLine("namespace Chatter.CQRS.SourceGenerated");
            sb.AppendLine("{");
            sb.AppendLine("    public static class GeneratedAllCommandsBehaviorRegistration");
            sb.AppendLine("    {");
            sb.AppendLine("        public static IServiceCollection RegisterAll(IServiceCollection services)");
            sb.AppendLine("        {");

            var emitted = false;

            foreach (var behaviorType in behaviorTypes.Distinct(SymbolEqualityComparer.Default).OfType<INamedTypeSymbol>())
            {
                if (!behaviorType.IsGenericType || behaviorType.Arity != 1 || !behaviorType.IsDefinition)
                {
                    continue;
                }

                if (!CompilationTypeWalker.TryGetClosedInterface(behaviorType, commandBehaviorOpen, out var closedOnOwnParameter))
                {
                    continue;
                }

                if (!SymbolEqualityComparer.Default.Equals(closedOnOwnParameter.TypeArguments[0], behaviorType.TypeParameters[0]))
                {
                    continue;
                }

                if (!compilation.IsSymbolAccessibleWithin(behaviorType, compilation.Assembly))
                {
                    continue;
                }

                foreach (var commandType in commandTypes)
                {
                    var closedBehavior = behaviorType.Construct(commandType);
                    sb.AppendLine($"            services.AddCommandBehavior<{CompilationTypeWalker.FullyQualifiedName(commandType)}, {CompilationTypeWalker.FullyQualifiedName(closedBehavior)}>();");
                    emitted = true;
                }
            }

            sb.AppendLine("            return services;");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            if (emitted)
            {
                context.AddSource("GeneratedAllCommandsBehaviorRegistration.g.cs", sb.ToString());
            }
        }
    }
}
