using System.Linq;
using System.Text;
using Chatter.SourceGenerators.Discovery;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace Chatter.SourceGenerators
{
    [Generator(LanguageNames.CSharp)]
    public sealed class BrokeredMessageReceiverRegistrationGenerator : IIncrementalGenerator
    {
        private const string MessageInterfaceMetadataName = "Chatter.CQRS.IMessage";
        private const string BrokeredMessageAttributeMetadataName = "Chatter.MessageBrokers.BrokeredMessageAttribute";
        private const string ReceiverOptionsMetadataName = "Chatter.MessageBrokers.Receiving.ReceiverOptions";
        private const string ChatterMessageBrokersAssemblySimpleName = "Chatter.MessageBrokers";

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            context.RegisterSourceOutput(context.CompilationProvider, static (spc, compilation) => Execute(compilation, spc));
        }

        private static void Execute(Compilation compilation, SourceProductionContext context)
        {
            var messageInterface = compilation.GetTypeByMetadataName(MessageInterfaceMetadataName);
            var brokeredMessageAttribute = compilation.GetTypeByMetadataName(BrokeredMessageAttributeMetadataName);
            var receiverOptions = compilation.GetTypeByMetadataName(ReceiverOptionsMetadataName);

            if (messageInterface is null || brokeredMessageAttribute is null || receiverOptions is null)
            {
                return;
            }

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
            sb.AppendLine("namespace Chatter.MessageBrokers.SourceGenerated");
            sb.AppendLine("{");
            sb.AppendLine("    public static class GeneratedReceiverRegistration");
            sb.AppendLine("    {");
            sb.AppendLine("        public static IServiceCollection RegisterAll(IServiceCollection services)");
            sb.AppendLine("        {");

            var emitted = false;

            foreach (var candidate in CompilationTypeWalker.FindAccessibleCandidateTypes(compilation, ChatterMessageBrokersAssemblySimpleName))
            {
                if (!CompilationTypeWalker.Implements(candidate, messageInterface))
                {
                    continue;
                }

                var attributeData = candidate.GetAttributes()
                    .FirstOrDefault(a => SymbolEqualityComparer.Default.Equals(a.AttributeClass, brokeredMessageAttribute));

                if (attributeData is null || attributeData.ConstructorArguments.Length < 6)
                {
                    continue;
                }

                var args = attributeData.ConstructorArguments;
                var receivingPath = args[1].Value as string;

                if (string.IsNullOrWhiteSpace(receivingPath))
                {
                    continue;
                }

                var sendingPath = args[0].Value as string;
                var errorQueueName = args[2].Value as string;
                var messageDescription = args[3].Value as string;
                var infrastructureType = args[4].Value as string;
                var deadletterQueueName = args[5].Value as string;

                sb.AppendLine($"            services.AddReceiver<{CompilationTypeWalker.FullyQualifiedName(candidate)}>(new global::Chatter.MessageBrokers.Receiving.ReceiverOptions");
                sb.AppendLine("            {");
                sb.AppendLine($"                MessageReceiverPath = {Literal(receivingPath)},");
                sb.AppendLine($"                SendingPath = {Literal(sendingPath)},");
                sb.AppendLine($"                ErrorQueuePath = {Literal(errorQueueName)},");
                sb.AppendLine($"                Description = {Literal(messageDescription)},");
                sb.AppendLine($"                InfrastructureType = {Literal(infrastructureType ?? string.Empty)},");
                sb.AppendLine($"                DeadLetterQueuePath = {Literal(deadletterQueueName)},");
                sb.AppendLine("                TransactionMode = null,");
                sb.AppendLine("            });");
                emitted = true;
            }

            sb.AppendLine("            return services;");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            if (emitted)
            {
                context.AddSource("GeneratedReceiverRegistration.g.cs", sb.ToString());
            }
        }

        private static string Literal(string? value)
            => value is null ? "null" : SymbolDisplay.FormatLiteral(value, quote: true);
    }
}
