using System.Text;
using Chatter.SourceGenerators.Discovery;
using Microsoft.CodeAnalysis;

namespace Chatter.SourceGenerators
{
    [Generator(LanguageNames.CSharp)]
    public sealed class HandlerRegistrationGenerator : IIncrementalGenerator
    {
        private const string MessageHandlerOpenMetadataName = "Chatter.CQRS.IMessageHandler`1";
        private const string QueryHandlerOpenMetadataName = "Chatter.CQRS.Queries.IQueryHandler`2";
        private const string CommandMetadataName = "Chatter.CQRS.Commands.ICommand";
        private const string EventMetadataName = "Chatter.CQRS.Events.IEvent";
        private const string ChatterCqrsAssemblySimpleName = "Chatter.CQRS";

        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            context.RegisterSourceOutput(context.CompilationProvider, static (spc, compilation) => Execute(compilation, spc));
        }

        private static void Execute(Compilation compilation, SourceProductionContext context)
        {
            var messageHandlerOpen = compilation.GetTypeByMetadataName(MessageHandlerOpenMetadataName);
            var queryHandlerOpen = compilation.GetTypeByMetadataName(QueryHandlerOpenMetadataName);

            if (messageHandlerOpen is null && queryHandlerOpen is null)
            {
                return;
            }

            var commandInterface = compilation.GetTypeByMetadataName(CommandMetadataName);
            var eventInterface = compilation.GetTypeByMetadataName(EventMetadataName);

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
            sb.AppendLine("namespace Chatter.CQRS.SourceGenerated");
            sb.AppendLine("{");
            sb.AppendLine("    public static class GeneratedHandlerRegistration");
            sb.AppendLine("    {");
            sb.AppendLine("        public static IServiceCollection RegisterAll(IServiceCollection services)");
            sb.AppendLine("        {");

            var emitted = false;

            foreach (var candidate in CompilationTypeWalker.FindAccessibleCandidateTypes(compilation, ChatterCqrsAssemblySimpleName))
            {
                if (messageHandlerOpen is not null
                    && CompilationTypeWalker.TryGetClosedInterface(candidate, messageHandlerOpen, out var closedMessageHandler)
                    && closedMessageHandler.TypeArguments[0] is INamedTypeSymbol messageType)
                {
                    if (commandInterface is not null && CompilationTypeWalker.Implements(messageType, commandInterface))
                    {
                        sb.AppendLine($"            services.AddCommandHandler<{CompilationTypeWalker.FullyQualifiedName(messageType)}, {CompilationTypeWalker.FullyQualifiedName(candidate)}>();");
                        emitted = true;
                    }
                    else if (eventInterface is not null && CompilationTypeWalker.Implements(messageType, eventInterface))
                    {
                        sb.AppendLine($"            services.AddEventHandler<{CompilationTypeWalker.FullyQualifiedName(messageType)}, {CompilationTypeWalker.FullyQualifiedName(candidate)}>();");
                        emitted = true;
                    }
                }

                if (queryHandlerOpen is not null
                    && CompilationTypeWalker.TryGetClosedInterface(candidate, queryHandlerOpen, out var closedQueryHandler))
                {
                    var queryType = closedQueryHandler.TypeArguments[0];
                    var resultType = closedQueryHandler.TypeArguments[1];
                    sb.AppendLine($"            services.AddQueryHandler<{CompilationTypeWalker.FullyQualifiedName(queryType)}, {CompilationTypeWalker.FullyQualifiedName(resultType)}, {CompilationTypeWalker.FullyQualifiedName(candidate)}>();");
                    emitted = true;
                }
            }

            sb.AppendLine("            return services;");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");

            if (emitted)
            {
                context.AddSource("GeneratedHandlerRegistration.g.cs", sb.ToString());
            }
        }
    }
}
